pokemon_lista = [ 
{'ID' : 1, 
'Sprite' : "Sprites/001-m.png",
'Som' : "Sounds/001 - Bulbasaur.wav",
'Nome' : "Bulbasauro", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' :  6.9, 'Altura' : 0.7, 
'Descricao' : "Pokemon Semente",
'Info' : """Por algum tempo após seu nascimento,cresce  ao se alimentar das sementes nas costas""" },

{'ID' : 2,
'Sprite' : "Sprites/002-m.png",
'Som' : "Sounds/002 - Ivysaur.wav",
'Nome' : "Ivysauro", 'Tipo_1' : "Planta", 'Tipo_2' :"Venenoso", 
'Peso' :  13, 'Altura' : 1, 
'Descricao' : "Pokemon Semente",
'Info' : "Quando o botão nas costas começa a inchar, um aroma doce flutua para indicar as flores que florescem" },

{'ID' : 3, 
'Sprite' : "Sprites/003-m.png",
'Som' : "Sounds/003 - Venusaur.wav",
'Nome' : "Venasauro", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso", 
'Peso' :  100, 'Altura' : 2, 
'Descricao' : "Pokemon Semente",
'Info' : "Após um dia chuvoso, a flor nas costas cheira mais forte. O perfume atrai outros Pokémon" },

{'ID' : 4, 
'Sprite' : "Sprites/004-m.png",
'Som' : "Sounds/004 - Charmander.wav",
'Nome' : "Charmander", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' :  8.5, 'Altura' : 0.6, 
'Descricao' : "Pokemon Lagarto",
'Info' : "O fogo na ponta da cauda é uma medida da sua vida. Se saudável, sua cauda queima intensamente"},

{'ID' : 5, 
'Sprite' : "Sprites/005-m.png",
'Som' : "Sounds/005 - Charmeleon.wav",
'Nome' : "Charmeleon", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' :  19, 'Altura' : 1.1, 
'Descricao' : "Pokemon Chamas",
'Info' : "Nas montanhas rochosas onde Charmeleon vive, suas caudas ardentes brilham à noite como estrelas" },

{'ID' : 6, 
'Sprite' : "Sprites/006-m.png",
'Som' : "Sounds/006 - Charizard.wav",
'Nome' : "Charizard", 'Tipo_1' : "Fogo", 'Tipo_2' : "Voador", 
'Peso' :  90.5, 'Altura': 1.7 , 
'Descricao' : "Pokemon Chamas",
'Info' : "Dizem que o fogo dos Charizards queima mais quente se tiver passado por batalhas duras" },

{'ID' : 7, 
'Sprite' : "Sprites/007-m.png",
'Som' : "Sounds/007 - Squirtle.wav",
'Nome' : "Squirtle", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' :  9, 'Altura': 0.5 , 
'Descricao' : "Pokemon Tartaura-jovem",
'Info' : "Ele se abriga em sua concha e depois revida com bicos de água a cada oportunidade"},

{'ID' : 8, 
'Sprite' : "Sprites/008-m.png",
'Som' : "Sounds/008 - Wartortle.wav",
'Nome' : "Wartortle", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' :  22.5, 'Altura': 1 , 
'Descricao' : "Pokemon tartaruga",
'Info' : "Diz-se que vive 10.000 anos.Sua cauda peluda é popular como um símbolo da longevidade" },

{'ID' : 9, 
'Sprite' : "Sprites/009-m.png",
'Som' : "Sounds/009 - Blastoise.wav",
'Nome' : "Blastoise", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' :  85.5, 'Altura': 1.6 , 
'Descricao' : "Pokemon Concha",
'Info' : "Os jatosde água que jorra dos canhões de foguetes em sau concha podem perfurar aço espesso"
},

{'ID' : 10,
'Sprite' : "Sprites/010-m.png",
'Som' : "Sounds/010 - Caterpie.wav",
'Nome' : "Caterpie", 'Tipo_1' : "Inseto", 'Tipo_2' : "",
'Peso' :  2.9, 'Altura': 0.3 , 
'Descricao' : "Pokemon Lagarta",
'Info' : "Ele libera um fedor de sua antena vermelha para repelir os inimigos. Cresce mudando repetidamente" },

{'ID' : 11, 
'Sprite' : "Sprites/011-m.png",
'Som' : "Sounds/011 - Metapod.wav",
'Nome' : "Metapode", 'Tipo_1' : "Inseto", 'Tipo_2' : "",
'Peso' :  9.9, 'Altura': 0.7 , 
'Descricao' : "Pokemon Crisálida",
'Info' : "Uma concha de aço duro protege seu corpo sensível. Ele silenciosamente suporta dificuldades enquanto aguarda a evolução" },

{'ID' : 12,
'Sprite' : "Sprites/012-m.png",
'Som' : "Sounds/012 - Butterfree.wav",
'Nome' : "Butterfree", 'Tipo_1' : "Inseto", 'Tipo_2': "Voador",
'Peso' : 32, 'Altura' : 1.1,
'Descricao' : "Pokemon Borboleta",
'Info' : "Ele Adora o mel das flores e pode localizar manchas de flores que possuem quantidades minúsculas de pólen"},

{'ID' : 13,
'Sprite' : "Sprites/013-m.png",
'Som' : "Sounds/013 - Weedle.wav",
'Nome' : "Weedle", 'Tipo_1' : "Inseto", 'Tipo_2' : "Venenoso",
'Peso' : 3.2, 'Altura' : 0.3,
'Descricao' : "Pokemon Lagarta Peluda",
'Info' : 'Come seu peso nas folhas todos os dias. Afasta os atacantes com a agulha na cabeça'},

{'ID' : 14,
'Sprite' : "Sprites/014-m.png",
'Som' : "Sounds/014 - Kakuna.wav",
'Nome' : "Kakuna", 'Tipo_1' : "Inseto", 'Tipo_2' : "Venenoso",
'Peso' : 10, 'Altura' : 0.6,
'Descricao' : "Pokemon Pupa",
'Info' : "Enquanto aguarda a evolução, esconde-se de predadores sob folhas e em recantos de galhos"},

{'ID' : 15,
'Sprite' : "Sprites/015-m.png",
'Som' : "Sounds/015 - Beedrill.wav",
'Nome' : "Beedrill", 'Tipo_1' : "Inseto", 'Tipo_2' : "Venenoso",
'Peso' : 29.5, 'Altura' : 1,
'Descricao' : "Pokemon Abelha venenosa",
'Info' : "Seu melhor ataque envolve voar em alta velocidade, golpear com agulhas de veneno e depois voar"},

{'ID' : 16,
'Sprite' : "Sprites/016-m.png",
'Som' : "Sounds/016 - Pidgey.wav",
'Nome' : "Pidgey", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 1.8, 'Altura' : 0.3,
'Descricao' : "Pokemon Passarinho",
'Info' : "É dócil e prefere evitar conflitos. Se pertubardo, no entanto, pode ferozmente reagir"},

{'ID' : 17,
'Sprite' : "Sprites/017-m.png",
'Som' : "Sounds/017 - Pidgeotto.wav",
'Nome' : "Pidgeotto", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 30, 'Altura' : 1.1,
'Descricao' : "Pokemon Passaro",
'Info' : "Voa sobre sue vasto território em busca de presas, derrubando-o com suas garras altamente desenvolvidas"},

{'ID' : 18,
'Sprite' : "Sprites/018-m.png",
'Som' : "Sounds/018 - Pidgeot.wav",
'Nome' : "Pidgeot", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 39.5, 'Altura' : 1.5,
'Descricao' : "Pokemon Passaro",
'Info' : "Voa sobre sue vasto território em busca de presas, derrubando-o com suas garras altamente desenvolvidas"},

{'ID' : 19,
'Sprite' : "Sprites/019-m.png",
'Som' : "Sounds/019 - Rattata.wav",
'Nome' : "Rattata", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 3.5, 'Altura' : 0.3,
'Descricao' : "Pokemon rato",
'Info' : "Ele procura comida o dia todo. Roe obejtos duros para desgastar suas presas, que crescem constantemente durante sua vida"},

{'ID' : 20,
'Sprite' : "Sprites/020-m.png",
'Som' : "Sounds/020 - Raticate.wav",
'Nome' : "Raticate", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 18.5, 'Altura' : 0.7,
'Descricao' : "Pokemon Ratazana",
'Info' : "Com suas presas longas, este pokemon surpreendemente viloento pode roer até mesmo concreto espesso com facilidade"},

{'ID' : 21,
'Sprite' : "Sprites/021-m.png",
'Som' : "Sounds/021 - Spearow.wav",
'Nome' : "Spearow", 'Tipo_1' : "Voador", 'Tipo_2': "Normal",
'Peso' : 2, 'Altura' : 0.3,
'Descricao' : "Pokemon Passarinho",
'Info' : "Bate suas pequenas asas ocupadas para voar. Usando o bico, ele procura presas na grama"},

{'ID' : 22,
'Sprite' : "Sprites/022-m.png",
'Som' : "Sounds/022 - Fearow.wav",
'Nome' : "Fearow", 'Tipo_1' : "Voador", "Tipo_2" : "Normal",
'Peso' : 38, 'Altura' : 1.2,
'Descricao' : 'Pokemon Bico',
'Info' : "Ele tem resistência para voar o dia inteiro em suas asas largas. Ele luta usando seu bico afiado"},

{'ID' : 23,
'Sprite' : "Sprites/023-m.png",
'Som' : "Sounds/023 - Ekans.wav",
'Nome' : "Ekans", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 6.9, 'Altura' : 2,
'Descricao' : "Pokemon Serpente",
'Info' : "Ele foge pela grama sem emitir nenhum som e atinge presas desavisadas por trás"},

{'ID' : 24,
'Sprite' : "Sprites/024-m.png",
'Som' : "Sounds/024 - Arbok.wav",
'Nome' : "Arbok" , 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 65, 'Altura' : 3.5,
'Descricao' : "Pokemon Serpente",
'Info' : "O padrão em sua barriga é de intimidação. Ele restringe os inimigos enquanto eles estão congelados de medo"},

{'ID' : 25,
'Sprite' : "Sprites/025-m.png",
'Som' : "Sounds/025 - Pikachu.wav",
'Nome' : "Pikachu", 'Tipo_1' : "Elétrico", 'Tipo_2' : "",
'Peso' : 6, 'Altura' : 0.4,
'Descricao' : "Pokemon rato elétrico",
'Info' : "Ocasionalmente, usa um choque elétrico para recarregar um companheiro Pikachu que está em um estado enfraquecido"},

{'ID' : 26,
'Sprite' : "Sprites/026-m.png",
'Som' : "Sounds/026 - Raichu.wav",
'Nome' : "Raichu", 'Tipo_1' : "Elétrico", 'Tipo_2' : "",
'Peso' : 30, 'Altura' : 0.8,
'Descricao' : "Pokemon rato elétrico",
'Info' : "Sua cauda descarrega eletricidade no chão, protegendo-a de ficar chocada"},

{'ID' : 27,
'Sprite' : "Sprites/027-m.png",
'Som' : "Sounds/027 - SandShrew.wav",
'Nome' : "Sandshrew", 'Tipo_1' : "Terra", 'Tipo_2' : "",
'Peso' : 12, 'Altura' : 0.6,
'Descricao' : "Pokemon Tatu",
'Info' :"Cava tocas profundas para viver. Quando em perigo, enrola o corpo para resistir a ataques"},

{'ID' : 28,
'Sprite' : "Sprites/028-m.png",
'Som' : "Sounds/028 - Sandslash.wav",
'Nome' : "Sandslash", 'Tipo_1' : "Terra", 'Tipo_2' : "", 
'Peso' : 29.5, 'Altura' : 1,
'Descricao' : "Pokemon Tatu",
'Info' : "Os espigões em seu corpo são compostos de sua pele endurecida. Ele rola e ataca os inimigos com seus espinhos"},

{'ID' : 29,
'Sprite' : "Sprites/029.png",
'Som' : "Sounds/029 - Nidoran (Female).wav",
'Nome' : "Nidoran ♀", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 7, 'Altura' : 0.4,
'Descricao' : "Pokemon agulha venenosa",
'Info' : "Embora não prefira lutar, mesmo uma gota do veneno que secreta das farpas pode ser fatal"},

{'ID' : 30,
'Sprite' : "Sprites/030.png",
'Som' : "Sounds/030 - Nidorina.wav",
'Nome' : "Nidorina", 'Tipo_1' : "Venenoso", 'Tipo_2' : "", 
'Peso' : 20, 'Altura' : 0.8,
'Descricao' : "Pokemon agulha venenosa",
'Info' : "Quando percebe o perigo, levanta todas as farpas do corpo. Essas farpas crescem mais lentamente que Nidorinos"},

{'ID' : 31,
'Sprite' : "Sprites/031.png",
'Som' : "Sounds/031 - Nidoqueen.wav",
'Nome' : "Nidoqueen", 'Tipo_1' : "Terra", 'Tipo_2' : "Venenoso",
'Peso' : 60, 'Altura' : 1.3,
'Descricao' : "Pokemon Broca",
'Info' : "Seu corpo inteiro é blindado com escamas duras. Protegerá os jovens em sua toca com sua vida."},

{'ID' : 32,
'Sprite' : "Sprites/032.png",
'Som' : "Sounds/032 - Nidoran (Male).wav",
'Nome' : "Nidoran ♂", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 9, 'Altura' : 0.5,
'Descricao' : "Pokemon agulha venenosa",
'Info' : "Ele examina seus arredores levantando as orelhas para fora da grama. Seu chifre tóxico é para proteção"},

{'ID' : 33,
'Sprite' : "Sprites/033.png",
'Som' : "Sounds/033 - Nidorino.wav",
'Nome' : "Nidorino", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 19.5, 'Altura' : 0.9,
'Descricao' : "Pokemon agulha venenosa",
'Info' : "Tem uma disposição violenta e apunhala os inimigos com seu chifre, que exala veneno após o impacto"},

{'ID' : 34,
'Sprite' : "Sprites/034.png",
'Som' : "Sounds/034 - Nidoking.wav",
'Nome' : "Nidoking", 'Tipo_1' : "Terra", 'Tipo_2': "Venenoso",
'Peso' : 62, 'Altura' : 1.4,
"Descricao" : "Pokemon Broca",
'Info' : "Um balanço de sua poderosa cauda pode quebrar um poste telefônico como se fosse um palito de fósforo"},

{'ID' : 35,
'Sprite' : "Sprites/035-m.png",
'Som' : "Sounds/035 - Clefairy.wav",
'Nome' : "Clefairy", 'Tipo_1' : "Fada", 'Tipo_2' : "",
'Peso' : 7.5, 'Altura' : 0.6,
'Descricao' : "Pokemon Fada",
'Info' : "Nas noites de lua cheia, Clefairy se reúne e dança. Tomar banho ao luar os faz flutuar"},

{'ID' : 36,
'Sprite' : "Sprites/036-m.png",
'Nome' : "Clefable", 'Tipo_1' : "Fada", 'Tipo_2' : "",
'Peso' : 40, 'Altura' : 1.3,
'Descricao' : "Pokemon Fada",
'Info' : "Seus ouvidos são sensíveis o suficiente para ouvir um alfinete cair a mais de um quilômetro de distância, então geralmente são encontrados em locais calmos"},

{'ID' : 37,
'Sprite' : "Sprites/037-m.png",
'Som' : "Sound/037 - Vulpix.war",
'Nome' : "Vulpix", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' : 9.9, 'Altura' : 0.6,
'Descricao' : "Pokemon Raposa",
'Info' : "À medida que cada cauda cresce, seu pêlo se torna mais brilhante. Quando segurado, parece um pouco quente"},

{'ID' : 38,
'Sprite' : "Sprites/038-m.png",
'Som' : "Sounds/038 - Ninetales.wav",
'Nome' : "Ninetales", 'Tipo_1' : "Fogo", 'Tipo_2' : "", 
'Peso' : 19.9, 'Altura' : 1.1,
'Descricao' : "Pokemon Raposa",
'Info' : "Cada uma de suas nove caudas é imbuída de poder sobrenatural e pode viver por mil anos"},

{'ID' : 39,
'Sprite' : "Sprites/039-m.png",
'Som' : "Sounds/039 - Jigglypuff.wav",
'Nome' : "Jigglypuff", 'Tipo_1' : "Fada", 'Tipo_2': "Normal",
'Peso' : 5.5, 'Altura' : 0.5,
'Descricao' : "Pokemon Balao",
'Info' : "Olhar para seus olhos redondos e bonitos faz com que comece a cantar uma música que os ouvintes agradáveis ​​não podem deixar de adormecer"},

{'ID' : 40,
'Sprite' : "Sprites/040-m.png",
'Som' : "Sounds/040 - Wigglytuff.wav",
'Nome' : "Wigglytuff", 'Tipo_1' : "Fada", 'Tipo_2': "Normal",
'Peso' : 12, 'Altura' : 1,
'Descricao' : "Pokemon Balao",
'Info' : "Sua pele fina é tão agradável que aqueles que a tocam acidentalmente não conseguem tirar as mãos"},

{'ID' : 41,
'Sprite' : "Sprites/041-m.png",
'Som' : "Sounds/041 - Zubat.wav",
'Nome' : "Zubat", 'Tipo_1' : "Venenoso", 'Tipo_2': "Voador",
'Peso' : 7.5, 'Altura' : 0.8,
'Descricao' : "Pokemon Morcego",
'Info' : "Ele não precisa de olhos, porque emite ondas ultrassônicas para verificar seus arredores enquanto voa"},

{'ID' : 42,
'Sprite' : "Sprites/042-m.png",
'Som' : "Sound/042 - Golbat.wav",
'Nome' : "Golbat", 'Tipo_1' : "Venenoso", 'Tipo_2' : "Voador",
'Peso' : 55, 'Altura' : 1.6,
'Descricao' : "Pokemon Morcego",
'Info' : "Voando na calada da noite, afunda suas presas em suas presas e drena uma quantidade quase fatal de sangue"},

{'ID' : 43,
'Sprite' : "Sprites/043-m.png",
'Som' : "Sounds/043 - Oddish",
'Nome' : "Oddish", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 5.4, 'Altura' : 0.5,
'Descricao' : 'Pokemon Erva',
'Info' : "Costuma plantar os pés de raiz no chão durante o dia e semeia sementes enquanto caminha à noite"},

{'ID' : 44,
'Sprite' : "Sprites/044-m.png",
'Som' : "Sounds/044 - Gloom.wav",
'Nome' : "Gloom", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 8.6, 'Altura' : 0.8,
'Descricao' : "Pokemon Erva",
'Info' : "O mel que escorre da boca cheira tão atroz que pode enrolar o nariz a mais de um quilômetro de distância"},

{'ID' : 45,
'Sprite' : "Sprites/045-m.png",
'Som' : "Sounds/045 - Vileplume.wav",
'Nome' : "Vileplume", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 18.6, 'Altura' : 1.2,
'Descricao' : "Pokemon Flor",
'Info' : "Suas pétalas são as maiores do mundo. Enquanto caminha, espalha pólen extremamente alergênico"},

{'ID' : 46,
'Sprite' : "Sprites/046-m.png",
'Som' : "Sounds/046 - Paras.wav",
'Nome' : "Paras", 'Tipo_1' : "Planta", 'Tipo_2' : "Inseto",
'Peso' : 5.4, 'Altura' : 0.3,
'Descricao' : "Pokemon Cogumelo",
'Info' : "Cogumelos chamados tochukaso crescem nas costas. Eles crescem junto com o anfitrião Paras"},

{'ID' : 47,
'Sprite' : "Sprites/047-m.png",
'Som' : "Sounds/047 - Parasect.wav",
'Nome' : "Parasect", 'Tipo_1' : "Planta", 'Tipo_2': "Inseto",
'Peso' : 29.5, 'Altura' : 1,
'Descricao' : "Pokemon Cogumelo",
'Info' : "Um cogumelo maior que o corpo hospedeiro controla o parasita. Espalha esporos venenosos"},

{'ID' : 48,
'Sprite' : "Sprites/048-m.png",
'Som' : "Sounds/048 - Venonat.wav",
'Nome' : "Venonat",  'Tipo_1' : "Inseto", 'Tipo_2': "Venenoso",
'Peso' : 30, 'Altura' : 1,
'Descricao' : "Pokemon Inseto",
'Info' : "Seus grandes olhos são na verdade aglomerados de pequenos olhos. À noite, é atraído pela luz."},

{'ID' : 49,
'Sprite' : "Sprites/049-m.png",
'Som' : "Sounds/049 - Venomoth.wav",
'Nome' : "Venomoth", 'Tipo_1' : "Inseto", 'Tipo_2' : "Venenoso",
'Peso' : 12.5, 'Altura' : 1.5,
'Descricao' : "Pokemon traca venenosa",
'Info' : "Ele bate as asas para espalhar escamas semelhantes a poeira. As escamas liberam toxinas se entrarem em contato com a pele"},

{'ID' : 50,
'Sprite' : "Sprites/050-m.png",
'Som' : "Sounds/050 - Diglett.wav",
'Nome' : "Diglett", 'Tipo_1' : "Terra", 'Tipo_2' : "",
'Peso' : 0.8, 'Altura' : 0.2,
'Descricao' : "Pokemon Toupeira",
'Info' : "Um Pokémon que vive no subsolo. Por causa de seu habitat escuro, é repelido pela luz do sol"},

{'ID' :  51,
'Sprite' : "Sprites/051-m.png",
'Som' : "Sounds/051 - Dugtrio.wav",
'Nome' : "Dugtrio", 'Tipo_1' : "Terra", 'Tipo_2' : "",
'Peso' : 33.3, 'Altura' : 0.7,
'Descricao' : "Pokemon Toupeira",
'Info' : 'Suas três cabeças se movem alternadamente, conduzindo-o através de solos difíceis a profundidades supeiores a 100 quilômetros'},

{'ID' : 52,
'Sprite' : "Sprites/052-m.png",
'Som' : "Sounds/052 - Meowth.wav",
'Nome' : "Meowth", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 4.2, 'Altura' : 0.4,
'Descricao' : "Pokemon Gatuno",
'Info' : "É de natureza nortuna. Se encontrar algo brilhante, seus olhos brilham intensamente"},

{'ID' : 53,
'Sprite' : "Sprites/053-m.png",
'Som' : "Sounds/053 - Persian.wav",
'Nome' : "Persian", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 32, 'Altura' : 1,
'Descricao' : "Pokemon Gato Siamês",
'Info' : "Um pokémon muito arrogante. Entre os fãs, o tamanho da jóia em sua testa é um assunto muito discutido"},

{'ID' : 54,
'Sprite' : "Sprites/054-m.png",
'Som' : "Sounds/054 - Psyduck.wav",
'Nome' : "Pysduck" , 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 19.6, 'Altura' : 0.8,
'Descricao' : "Pokemon Pato",
'Info' : "Quando as dores de cabeça estimulam suas células cerebrais, que geralmente são inativas, ele pode usar um poder misterioso"},

{'ID' : 55,
'Sprite' : "Sprites/055-m.png",
'Som' : "Sounds/056 - Golduck.wav",
'Nome' : "Golduck", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 76.6, 'Altura' : 1.7,
'Descricao' : "Pokémon pato",
'Info' : "Quando sua testa brilha misteriosamente, Golduck pode usar toda a extensão de seu poder"},

{'ID' : 56,
'Sprite' : "Sprites/056-m.png",
'Som' : "Sounds/056 - Mankey.wav",
'Nome' : "Mankey", 'Tipo_1' : "Lutador", 'Tipo_2' : "",
'Peso' : 28, 'Altura' : 0.5,
'Descricao' : "Pokémon Macaco Porco",
'Info' : "Ele vive em colônias das copas das árvores. Se alguém fica furioso, a colônia inteira se agita sem motivo"},

{'ID' : 57,
'Sprite' : "Sprites/057-m.png",
'Som' : "Sounds/057 - Primeape.wav",
'Nome' : "Primeape", 'Tipo_1' : "Lutador", 'Tipo_2' : "",
'Peso' : 32, 'Altura' : 1,
'Descricao' : "Pokémon Macaco Porco",
'Info' : "Ele fica bravo se você vê seus olhos e fica mais irritado se você correr. Se você vencer, fica ainda mais louco"},

{'ID' : 58,
'Sprite' : "Sprites/058-m.png",
'Som' : "Sounds/058 - Growlithe.wav",
'Nome' : "Growlithe", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' : 19, 'Altura' : 0.7,
'Descricao' : "Pokémon Filhote",
'Info' : "Extremamente leal ao seu treinador, ele latirá para aqueles que se aproximarem do treinador inesperadamente e os expulsarão da cidade"},

{'ID' : 59,
'Sprite' : "Sprites/059-m.png",
'Som' : "Sounds/059 - Arcanine.wav",
'Nome' : "Arcanine", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' : 155, 'Altura' : 1.9,
'Descricao' : "Pokemon Lenda",
'Info' : "A visão dele percorrendo mais de 10 mil quilômetros em um único dia e noite cativou muitas pessoas"},

{'ID' : 60,
'Sprite' : "Sprites/060-m.png",
'Som' : "Sounds/060 - Poiliwag.wav",
'Nome' : "Poliwag", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 12.4, 'Altura' : 0.6,
'Descricao' : "Pokémon Girino",
'Info' : "Sua pele é tão fina que seus órgãos internos são visíveis. Tem dificuldade para andar com os pés recém-crescidos"},

{'ID' : 61,
'Sprite' : "Sprites/061-m.png",
'Som' : "Sounds/061 - Poiliwhirl.wav",
'Nome' : "Poliwhirl", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 20, 'Altura' : 1,
'Descricao' : "Pokémon Girino",
'Info' : "O padrão espiral em sua barriga ondula sutilmente. Olhá-lo gradualmente causa sonolência" },

{'ID' : 62,
'Sprite' : "Sprites/062-m.png",
'Som' : "Sounds/062 - Poliwrath.wav",
'Nome' : "Poliwrath", 'Tipo_1' : "Água", 'Tipo_2' : "Lutador",
'Peso' : 54, 'Altura' : 1.3,
'Descricao' : "Pokémon Girino",
'Info' : "Com seus músculos extremamente resistentes, ele pode nadar no Oceano Pacífico sem descansar"},

{'ID' : 63,
'Sprite' : "Sprites/063-m.png",
'Som' : "Sounds/063 - Abra.wav",
'Nome' : "Abra", 'Tipo_1' : "Psíquico", 'Tipo_2' : "",
'Peso' : 19.5, 'Altura' : 0.9,
'Descricao' : "Pokémon de telecinese",
'Info' : "O uso de seu poder psíquico é uma tensão tão grande no cérebro que ele precisa dormir 18 horas por dia"},

{'ID' : 64,
'Sprite' : "Sprites/064-m.png",
'Som' : "Sounds/064 - Kadabra.wav",
'Nome' : "Kadabra", 'Tipo_1' : "Psíquico", 'Tipo_2' : "",
'Peso' : 56.5, 'Altura' : 1.3,
'Descricao' : "Pokémon de telecinese",
'Info' : "Ele encara sua colher de prata para focar sua mente. Emite mais ondas alfa ao fazê-lo"},

{'ID' : 65,
'Sprite' : "Sprites/065-m.png",
'Som' : "Sounds/065 - Alakazam.wav",
'Nome' : "Alakazam", 'Tipo_1' : "Psíquico", 'Tipo_2' : "",
'Peso' : 48, 'Altura' : 1.5,
'Descricao' : "Pokémon de telecinese",
'Info' : "Diz-se que as colheres apertadas em suas mãos foram criadas por seus poderes psíquicos"},
 
{'ID' : 66,
'Sprite' : "Sprites/066-m.png",
'Som' : "Sounds/066 - Machop.wav",
'Nome' : "Machop", 'Tipo_1' : "Lutador", 'Tipo_2' : "",
'Peso' : 19.5, 'Altura' : 0.8,
'Descricao' : "Pokémon Musculoso",
'Info' : "Embora pequeno em estatura, é poderoso o suficiente para levantar e lançar com facilidade um número de Geodude de uma só vez"},
 
{'ID' : 67,
'Sprite' : "Sprites/067-m.png",
'Som' : "Sounds/067 - Machoke.wav",
'Nome' : "Machoke", 'Tipo_1' : "Lutador", 'Tipo_2' : "",
'Peso' : 70.5, 'Altura' : 1.5, 
'Descricao' : "Pokémon Musculoso",
'Info' : "Felizmente, carrega carga pesada para endurecer. De boa vontade faz um trabalho duro para as pessoas"},

{'ID' : 68,
'Sprite' : "Sprites/068-m.png",
'Som' : "Sounds/068 - Machamp.wav",
'Nome' : "Machamp", 'Tipo_1' : "Lutador", 'Tipo_2' : "",
'Peso' : 130, 'Altura' : 1.6,
'Descricao': "Pokémon Musculoso",
'Info' : "Seus quatro braços musculosos batem nos inimigos com poderosos socos e costeletas a uma velocidade ofuscante"},

{'ID' : 69,
'Sprite' : "Sprites/069-m.png",
'Som' : "Sounds/069 - Belsprout.wav",
'Nome' : "Belsprout", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 4, 'Altura' : 0.7,
'Descricao' : "Pokémon Flores",
'Info' : "Prefere ambientes quentes e úmidos. É rápido em capturar presas com suas videiras"},

{'ID' : 70,
'Sprite' : "Sprites/070-m.png",
'Som' : "Sounds/070 - Weepinbell.wav",
'Nome' : "Weepinbell", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 6.4, 'Altura' : 1,
'Descricao' : "Pokémon papa-moscas",
'Info' : "Um Pokémon que parece ser uma planta. Ele captura presas incautas mergulhando-as com um pó tóxico"},

{'ID' : 71,
'Sprite' : "Sprites/071-m.png",
'Som' : "Sounds/071 - Victreebel.wav",
'Nome' : "Victreebel", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 15.5, 'Altura' : 1.7,
'Descricao' : "Pokémon papa-moscas",
'Info' : "Ele acumula na boca um fluido com um perfume semelhante ao mel, que é realmente um ácido que dissolve qualquer coisa."},

{'ID' : 72,
'Sprite' : "Sprites/072-m.png",
'Som' : "Sounds/072 - Tentacool.wav",
'Nome' : "Tentacool", 'Tipo_1' : "Água", 'Tipo_2' : "Venenoso",
'Peso' : 45.5, 'Altura' : 0.9,
'Descricao' : "Pokémon Água-viva",
'Info' : "Como seu corpo é quase inteiramente composto de água, ele encolhe se for lavado em terra"},

{'ID' : 73,
'Sprite' : "Sprites/073-m.png",
'Som' : "Sounds/073 - Tentacruel.wav",
'Nome' : "Tentacruel", 'Tipo_1' : "Água", 'Tipo_2' : "Venenoso",
'Peso' : 55, 'Altura' : 1.6,
'Descricao' : "Pokémon Água Viva",
'Info' : "Ele estende seus 80 tentáculos para formar uma rede venenosa que é difícil de escapar"},

{'ID' : 74,
'Sprite' : "Sprites/074-m.png",
'Som' : "Sounds/074 - Geodude.wav",
'Nome' : "Geodude", 'Tipo_1' : "Rocha", 'Tipo_2' : "Terra",
'Peso' : 20, 'Altura' : 0.4,
'Descricao' : "Pokémon Rocha",
'Info' : "Em repouso, parece uma rocha. Pisá-lo descuidadamente o fará girar os punhos com raiva"},

{'ID' : 75,
'Sprite' : "Sprites/075-m.png",
'Som' : "Sounds/075 - Graveler.wav",
'Nome' : "Graveler", 'Tipo_1' : "Rocha", 'Tipo_2' : "Terra",
'Peso' : 105, 'Altura' : 1,
'Descricao' : "Pokémon Rocha",
'Info' : "Ele rola nos caminhos das montanhas para se mover. Uma vez que cria impulso, nenhum Pokémon pode pará-lo sem dificuldade"},

{'ID' : 76,
'Sprite' : "Sprites/076-m.png",
'Som' : "Sounds/076 - Golem.wav",
'Nome' : "Golem", 'Tipo_1' : "Rocha", 'Tipo_2' : "Terra",
'Peso' : 300, 'Altura' : 1.4,
'Descricao' : "Pokémon Megaton",
'Info' : "Mesmo a dinamite não pode prejudicar seu corpo duro e parecido com uma rocha. Ele se esconde apenas uma vez por ano"},

{'ID' : 77,
'Sprite' : "Sprites/077-m.png",
'Som' : "Sounds/077 - Ponyta.wav",
'Nome' : "Ponyta", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' : 30, 'Altura' : 1,
'Descricao' : "Pokémon Cavalo de Fogo",
'Info' : "Como um recém-nascido, ele mal consegue suportar. No entanto, através do galope, suas pernas ficam mais duras e rápidas"},

{'ID' : 78,
'Sprite' : "Sprites/078-m.png",
'Som' : "Sounds/078 - Rapidash.wav",
'Nome' : "Rapidash", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' : 95, 'Altura' : 1.7,
'Descricao' : "Pokémon Cavalo de Fogo",
'Info' : "Quando a galope, sua juba ardente brilha, melhorando sua bela aparência"},

{'ID' : 79,
'Sprite' : "Sprites/079-m.png",
'Som' : "Sounds/079 - Slowpoke.wav",
'Nome' : "Slowpoke", 'Tipo_1' : "Psíquico", 'Tipo_2' : "Água",
'Peso' : 36, 'Altura' : 1.2,
'Descricao' : "Pokémon Estúpido",
'Info' : "Embora lento, é hábil em pescar com a cauda. Não sente dor se sua cauda é mordida"},

{'ID' : 80,
'Sprite' : "Sprites/080-m.png",
'Som' : "Sounds/080 - Slowbro.wav",
'Nome' : "Slowbro", 'Tipo_1' : "Psíquico", 'Tipo_2' : "Água",
'Peso' : 78.5, 'Altura' : 1.6,
'Descricao' : "Pokémon Caranguejo Eremita",
'Info' : "Embora seja geralmente tolo, parece inspirado se o Shellder em sua cauda morder"},

{'ID' : 81,
'Sprite' : "Sprites/081.png",
'Som' : "Sounds/081 - Magnemite.wav",
'Nome' : "Magnemite", 'Tipo_1' : "Elétrico", 'Tipo_2' : "Aço",
'Peso' : 6, 'Altura' : 0.3,
'Descricao' : "Pokémon Magnético",
'Info' : "As ondas eletromagnéticas emitidas pelas unidades nas laterais da cabeça expelem a antigravidade, o que lhe permite flutuar"},

{'ID' : 82,
'Sprite' : "Sprites/082.png",
'Som' : "Sounds/083 - Magneton.wav",
'Nome' : "Magneton", 'Tipo_1' : "Elétrico", 'Tipo_2' : "Aço",
'Peso' : 60, 'Altura' : 1,
'Descricao' : "Pokémon Magnético",
'Info' : "As fortes ondas eletromagnéticas dos três magnemitas ligados são suficientes para secar a umidade ao redor"},

{'ID' : 83,
'Sprite' : "Sprites/083-m.png",
'Som' : "Sounds/083 - Farfetch'd.wav",
'Nome' : "Farfetch'd", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 15, 'Altura' : 0.8,
'Descricao' : "Pokémon pato pontual",
'Info' : "Não pode viver sem o talo que segura. É por isso que defende o caule dos atacantes com sua vida"},

{'ID' : 84,
'Sprite' : "Sprites/084-m.png",
'Som' : "Sounds/084 - Doduo.wav",
'Nome' : "Doduo", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 39.2, 'Altura' : 1.4,
'Descricao' : "Pokémon Pássaro Gêmeos",
'Info' : "Os cérebros em suas duas cabeças parecem comunicar emoções um ao outro com um poder telepático"},

{'ID' : 85,
'Sprite' : "Sprites/085-m.png",
'Som' : "Sounds/085 - Dodrio.wav",
'Nome' : "Dodrio", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 85.2, 'Altura' : 1.8,
'Descricao' : "Pokémon Pássaro Tripleto",
'Info' : "Quando Doduo evolui para esta raça estranha, uma de suas cabeças se divide em duas. Funciona a quase 40 mph"},

{'ID' : 86,
'Sprite' : "Sprites/086-m.png",
'Som' : "Sounds/086 - Seel.wav",
'Nome' : "Seel", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 90, 'Altura' : 1.1,
'Descricao' : "Pokémon-leão-marinho",
'Info' : "Quanto mais frio fica, melhor se sente. Nadar alegremente em torno dos oceanos tão frios que são preenchidos com gelo flutuante"},

{'ID' : 87,
'Sprite' : "Sprites/087-m.png",
'Som' : "Sounds/087 - Dewgong.wav",
'Nome' : "Dewgong", 'Tipo_1' : "Gelo", 'Tipo_2' : "Água",
'Peso' : 120, 'Altura' : 1.7,
'Descricao' : "Pokémon-leão-marinho",
'Info' : "Seu corpo aerodinâmico tem baixa resistência e nada em oceanos frios a uma velocidade de oito nós"},

{'ID' : 88,
'Sprite' : "Sprites/088-m.png",
'Som' : "Sounds/088 - Grimer.wav",
'Nome' : "Grimer", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 30, 'Altura' : 0.9,
'Descricao' : "Pokémon de Lodo",
'Info' : "Nascidos do lodo, esses Pokémon agora se reúnem em lugares poluídos e aumentam as bactérias em seus corpos"},

{'ID' : 89,
'Sprite' : "Sprites/089-m.png",
'Som' : "Sounds/089 - Muk.wav",
'Nome' : "Muk", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 30, 'Altura' : 1.2,
'Descricao' : "Pokémon de Lodo",
'Info' : "É tão fedido! O corpo de Muks contém elementos tóxicos, e qualquer planta murcha quando passa"},

{'ID' : 90,
'Sprite' : "Sprites/090-m.png",
'Som' : "Sounds/090 - Shellder.wav",
'Nome' : "Shellder", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 4, 'Altura' : 0.3,
'Descricao' : "Pokémon Bivalves",
'Info' : "Nada para trás abrindo e fechando suas duas conchas. Sua língua grande é sempre mantida pendurada."}, 

{'ID' : 91,
'Sprite' : "Sprites/091-m.png",
'Som' : "Sounds/091 - Cloyster.wav",
'Nome' : "Cloyster", 'Tipo_1' : "Gelo", 'Tipo_2' : "Água",
'Peso' : 132.5, 'Altura' : 1.5,
'Descricao' :"Pokémon Bivalves",
'Info' : "Ele luta mantendo a concha firmemente fechada para proteção e disparando espigas para repelir os inimigos"},

{'ID' : 92,
'Sprite' : "Sprites/092-m.png",
'Som' : "Sounds/092 - Gastly.wav",
'Nome' : "Gastly", 'Tipo_1' : "Fantasma", 'Tipo_2' : "Venenoso",
'Peso' : 0.1, 'Altura' : 1.3,
'Descricao' : "Pokémon Gasoso",
'Info' : "Nascido a partir de gases, qualquer um desmaia se for engolido por seu corpo gasoso, que contém veneno"},

{'ID' : 93,
'Sprite' : "Sprites/093-m.png",
'Som' : "Sounds/093 - Haunter.wav",
'Nome' : "Haunter", 'Tipo_1' : "Fantasma", 'Tipo_2' : "Venenoso",
'Peso' : 0.1, 'Altura' : 1.6,
'Descricao' : "Pokémon Gasoso",
'Info' : "Gosta de espreitar no escuro e bater nos ombros com uma mão gasosa. Seu toque causa tremores sem fim"},

{'ID' : 94,
'Sprite' : "Sprites/094-m.png",
'Som' : "Sounds/094 - Gengar.wav",
'Nome' : "Gengar", 'Tipo_1' : "Fantasma", 'Tipo_2' : "Venenoso",
'Peso' : 40.5, 'Altura' : 1.5,
'Descricao' : "Pokemon das Sombras",
'Info' : "O olhar malicioso que flutua na escuridão pertence a um Gengar que se deleita em lançar maldições às pessoas"},

{'ID' : 95,
'Sprite' : "Sprites/095-m.png",
'Som' : "Sounds/095 - Onix.wav",
'Nome' : "Onix", 'Tipo_1' : "Rocha", 'Tipo_2' : "Terra",
'Peso' : 210, 'Altura' : 8.8,
'Descricao' : "Pokémon Serpente da Rocha",
'Info' : "Ao abrir sua boca grande, ingere grandes quantidades de solo e cria longos túneis"},

{'ID' : 96,
'Sprite' : "Sprites/096-m.png",
'Som' : "Sounds/096 - Drowzee.wav",
'Nome' : "Drowzee", 'Tipo_1' : "Psíquico", 'Tipo_2' : "",
'Peso' : 32.4, 'Altura' : 1,
'Descricao' : "Pokémon da hipnose",
'Info' : "Ele pode dizer o que as pessoas estão sonhando cheirando o nariz grande. Adora sonhos divertidos"},

{'ID' : 97,
'Sprite' : "Sprites/097-m.png",
'Som' : "Sounds/097 - Hypno.wav",
'Nome' : "Hypno", 'Tipo_1' : "Psíquico", 'Tipo_2' : "",
'Peso' : 75.6, 'Altura' : 1.6,
'Descricao' : "Pokémon da hipnose",
'Info' : "Ver seu pêndulo oscilante pode induzir o sono em três segundos, mesmo em alguém que acabou de acordar"},

{'ID' : 98,
'Sprite' : "Sprites/098-m.png",
'Som' : "Sounds/098 - Krabby.wav",
'Nome' : "Krabby", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 6.5, 'Altura' : 0.4,
'Descricao' : "Pokémon de caranguejo",
'Info' : "Ele vive em tocas cavadas em praias arenosas. Suas pinças crescem totalmente se forem quebradas na batalha"},

{'ID' : 99,
'Sprite' : "Sprites/099-m.png",
'Som' : "Sounds/099 - Kingler.wav",
'Nome' : "Kingler", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 60, 'Altura' : 1.3,
'Descricao' : "Pokémon Pinça",
'Info' : "A pinça maior possui uma força de 10.000 cavalos de potência. No entanto, é tão pesado que é difícil mirar"},

{'ID' : 100,
'Sprite' : "Sprites/100.png",
'Som' : "Sounds/100 - Voltorb.wav",
'Nome' : "Voltorb", 'Tipo_1' : "Elétrico", 'Tipo_2' : "",
'Peso' : 10.4, 'Altura' : 0.5,
'Descricao' : "Pokémon Bola",
'Info' : "Parece uma Pok Pok. É perigoso porque pode eletrocutar ou explodir em contato"},

{'ID' : 101,
'Sprite' : "Sprites/101.png",
'Som' : "Sounds/101 - Electrode.wav",
'Nome' : "Electrode", 'Tipo_1' : "Elétrico", 'Tipo_2' : "",
'Peso' : 66.6, 'Altura' : 1.2,
'Descricao' : "Pokémon Bola",
'Info' : "Sabe-se que ele flutua nos ventos se estiver cheio de eletricidade armazenada"},

{'ID' : 102,
'Sprite' : "Sprites/102-m.png",
'Som' : "Sounds/102 - Exeggcute.wav",
'Nome' : "Exeggcute", 'Tipo_1' : "Psíquico", 'Tipo_2' : "Planta",
'Peso' : 2.5, 'Altura' : 0.4,
'Descricao' : "Pokémon Ovo",
'Info' : "Seus seis ovos conversam usando telepatia. Eles podem se reunir rapidamente se forem separados"},

{'ID' : 103,
'Sprite' : "Sprites/103-m.png",
'Som' : "Sounds/103 - Exeggutor.wav",
'Nome' : "Exeggutor", 'Tipo_1' : "Psíquico", 'Tipo_2' : "Planta",
'Peso' : 120, 'Altura' : 2,
'Descricao' : "Pokémon Coqueiro",
'Info' : "É chamado The Walking Jungle. Se uma cabeça cresce muito, ela cai e se torna um Exeggcute"},

{'ID' : 104,
'Sprite' : "Sprites/104-m.png",
'Som' : "Sounds/104 - Cubone.wav",
'Nome' : "Cubone", 'Tipo_1' : "Terra", 'Tipo_2' : "",
'Peso' : 6.5, 'Altura' : 0.4,
'Descricao' : "Pokémon Solitário",
'Info' : "Quando pensa em sua mãe morta, chora. Seu choro faz o crânio que usa chocalhar oco"},

{'ID' : 105,
'Sprite' : "Sprites/105-m.png",
'Som' : "Sounds/105 - Marowak.wav",
'Nome' : "Marowak", 'Tipo_1' : "Terra", 'Tipo_2' : "",
'Peso' : 45, 'Altura' : 1,
'Descricao' : "Pokémon Amante de Ossos",
'Info' :  "Desde o seu nascimento, este Pokémon selvagem mantém constantemente ossos. É hábil em usá-los como armas"},

{'ID' : 106,
'Sprite' : "Sprites/106.png",
'Som' : "Sounds/106 - Hitmonlee.wav",
'Nome' : 'Hitmonlee', 'Tipo_1' : "Lutador", 'Tipo_2' : "",
'Peso' : 49.8, 'Altura' : 1.5,
'Descricao' : "Pokemon chute",
'Info' : "Suas pernas podem se esticar duas vezes. Inimigos pela primeira vez são surpreendidos por seu alcance extensível"},

{'ID' : 107,
'Sprite' : "Sprites/107.png",
'Som' : "Sounds/107 - Hitmonchan.wav",
'Nome' : "Hitmonchan", 'Tipo_1' : "Lutador", 'Tipo_2' : "",
'Peso' : 50.2, 'Altura' : 1.4,
'Descricao' : "Pokemon Soco",
'Info' : "Os socos que ele torce os braços pulverizam até o concreto. Descansa após três minutos de Luta"},

{'ID' : 108,
'Sprite' : "Sprites/108-m.png",
'Som' : "Sounds/108 - Lickitung.wav",
'Nome': "Lickitung", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 66.5, 'Altura' : 1.2,
'Descricao' : "Pokemon Lambida",
'Info' : "Ser lambido por sua língua comprida e coberta de saliva deixa uma sensação de formigamento. Estender a língua retrai a cauda"},

{'ID' : 109,
'Sprite' : "Sprites/109-m.png",
'Som' : "Sounds/109 - Koffing.wav",
'Nome' : "Koffing", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 1, 'Altura' : 0.6,
'Descricao' : "Pokemon gás venenoso",
'Info' : "O gás tóxico é mantido dentro de seu corpo fino e em forma de balão, para que possa causar explosões maciças"},

{'ID' : 110,
'Sprite' : "Sprites/110-m.png",
'Som' : "Sounds/110 - Weezing.wav",
'Nome' : "Weezing", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 9.5, 'Altura' : 1.2,
'Descricao' : "Pokemon gás venenoso",
'Info' : "A inalação de vapores tóxicos de lixo e a mistura denro de seu corpo permite espalhar um cheiro mais sujo"},

{'ID' : 111,
'Sprite' : "Sprites/111-m.png",
'Som' : "Sounds/111 - Rhyhorn.wav",
'Nome' : "Rhyhorn", 'Tipo_1' : "Rocha", 'Tipo_2' : "Terra",
'Peso' : 115, 'Altura' : 1,
'Descricao' : "Pokemon espetada",
'Info' : "Seus equipamentos poderosos podem destruir qualquer coisa. No entanto, é muito lento para ajudar as pessoas a trabalhar"},

{'ID' : 112,
'Sprite' : "Sprites/112-m.png",
'Som' : "Sounds/112 - Rhydon.wav",
'Nome' : "Rhydon", 'Tipo_1' : "Rocha", 'Tipo_2' : "Terra",
'Peso' : 120, 'Altura' : 1.9,
'Descricao' : "Pokemon Broca",
'Info' : 'Ficar de pé sobre as patas traseiras liberou as pernas da frente e as tornou mais inteligentes. É muit esquecido, no entanto' },

{'ID' : 113,
'Sprite' : "Sprites/113.png",
'Som' : "Sounds/113 - Chansey.wav",
'Nome' : "Chansey", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 34.6, 'Altura' : 1.1,
'Descricao' : "Pokemon enfermeira",
'Info' : "Um pokemon gentil que põe ovos altaamente nutritivos e os compartilha com pokemon ou pessoas feridas"},

{'ID' : 114,
'Sprite' : "Sprites/114-m.png",
'Som' : "Sounds/114 - Tangela.wav",
'Nome' : "Tangela", 'Tipo_1' : "Planta", 'Tipo_2' : "",
'Peso' : 35, 'Altura' : 1,
'Descricao' : "Pokemon Vinha",
'Info' : "Muitas videiras se contorcem e sua verdadeira identidade permanece desconhecida. As videiras azuis crescem por toda a vida"},

{'ID' : 115,
'Sprite' : "Sprites/115.png",
'Som' : "Sounds/115 - Kangaskhan.wav",
'Nome' : "KangasKhan", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 80, 'Altura' : 2.2,
'Descricao' : "Pokemon Pai e Filho",
'Info' : "Cria a sua prole na bolsa da barriga. Ele permite que o bebê brinque apenas quando se sentir seguro"},

{'ID' : 116,
'Sprite' : "Sprites/116-m.png",
'Som' : "Sounds/116 - Horsea.wav",
'Nome' : "Horsea", 'Tipo_1' : 'Água', 'Tipo_2' : "",
'Peso' : 8, 'Altura' : 0.4,
'Descricao' : "Pokemon Cavalo-Marinho",
'Info' : "Faz seu ninho à sombra dos corais. Se sente perigo, cospe tinta escura e foge"},

{'ID' : 117,
'Sprite' : "Sprites/117-m.png",
'Som' : "Sounds/117 - Seadra.wav",
'Nome' : "Seadra", 'Tipo_1' : 'Água', 'Tipo_2' : "",
'Peso' : 25, 'Altura' : 1.2,
'Descricao' : "Pokemon Dragão-Marinho",
'Info' : "Seus espinhos fornecem proteção. Suas Barbatanas e ossos são apreciados como ingredientes da medicina tradicional"}
]

# for id_pokemon, pokemon in enumerate(pokemon_lista):
#          print(f'#{id_pokemon + 1:0>3} - {pokemon["Tipo_1"]} / {pokemon["Tipo_2"]}')
