pokemon_lista = [ 
{'ID' : 1, 
'Sprite' : "Sprites/001-m.png",
'Nome' : "Bulbasauro", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' :  6.9, 'Altura' : 0.7, 
'Descricao' : "Pokemon Semente",
'Info' : "Por algum tempo após seu nascimento, cresce  ao se alimentar das sementes nas costas" },

{'ID' : 2,
'Sprite' : "Sprites/002-m.png",
'Nome' : "Ivysauro", 'Tipo_1' : "Planta", 'Tipo_2' :"Venenoso", 
'Peso' :  13, 'Altura' : 1, 
'Descricao' : "Pokemon Semente",
'Info' : "Quando o botão nas costas começa a inchar, um aroma doce flutua para indicar as flores que florescem" },

{'ID' : 3, 
'Sprite' : "Sprites/003-m.png",
'Nome' : "Venasauro", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso", 
'Peso' :  100, 'Altura' : 2, 
'Descricao' : "Pokemon Semente",
'Info' : "Após um dia chuvoso, a flor nas costas cheira mais forte. O perfume atrai outros Pokémon" },

{'ID' : 4, 
'Sprite' : "Sprites/004-m.png",
'Nome' : "Charmander", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' :  8.5, 'Altura' : 0.6, 
'Descricao' : "Pokemon Lagarto",
'Info' : "O fogo na ponta da cauda é uma medida da sua vida. Se saudável, sua cauda queima intensamente"},

{'ID' : 5, 
'Sprite' : "Sprites/005-m.png",
'Nome' : "Charmeleon", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' :  19, 'Altura' : 1.1, 
'Descricao' : "Pokemon Chamas",
'Info' : "Nas montanhas rochosas onde Charmeleon vive, suas caudas ardentes brilham à noite como estrelas" },

{'ID' : 6, 
'Sprite' : "Sprites/006-m.png",
'Nome' : "Charizard", 'Tipo_1' : "Fogo", 'Tipo_2' : "Voador", 
'Peso' :  90.5, 'Altura': 1.7 , 
'Descricao' : "Pokemon Chamas",
'Info' : "Dizem que o fogo dos Charizards queima mais quente se tiver passado por batalhas duras" },

{'ID' : 7, 
'Sprite' : "Sprites/007-m.png",
'Nome' : "Squirtle", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' :  9, 'Altura': 0.5 , 
'Descricao' : "Pokemon Tartaura-jovem",
'Info' : "Ele se abriga em sua concha e depois revida com bicos de água a cada oportunidade"},

{'ID' : 8, 
'Sprite' : "Sprites/008-m.png",
'Nome' : "Wartortle", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' :  22.5, 'Altura': 1 , 
'Descricao' : "Pokemon tartaruga",
'Info' : "Diz-se que vive 10.000 anos.Sua cauda peluda é popular como um símbolo da longevidade" },

{'ID' : 9, 
'Sprite' : "Sprites/009-m.png",
'Nome' : "Blastoise", 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' :  85.5, 'Altura': 1.6 , 
'Descricao' : "Pokemon Concha",
'Info' : "Os jatosde água que jorra dos canhões de foguetes em sau concha podem perfurar aço espesso"
},

{'ID' : 10,
'Sprite' : "Sprites/010-m.png",
'Nome' : "Caterpie", 'Tipo_1' : "Inseto", 'Tipo_2' : "",
'Peso' :  2.9, 'Altura': 0.3 , 
'Descricao' : "Pokemon Lagarta",
'Info' : "Ele libera um fedor de sua antena vermelha para repelir os inimigos. Cresce mudando repetidamente" },

{'ID' : 11, 
'Sprite' : "Sprites/011-m.png",
'Nome' : "Metapode", 'Tipo_1' : "Inseto", 'Tipo_2' : "",
'Peso' :  9.9, 'Altura': 0.7 , 
'Descricao' : "Pokemon Crisálida",
'Info' : "Uma concha de aço duro protege seu corpo sensível. Ele silenciosamente suporta dificuldades enquanto aguarda a evolução" },

{'ID' : 12,
'Sprite' : "Sprites/012-m.png",
'Nome' : "Butterfree", 'Tipo_1' : "Inseto", 'Tipo_2': "Voador",
'Peso' : 32, 'Altura' : 1.1,
'Descricao' : "Pokemon Borboleta",
'Info' : "Ele Adora o mel das flores e pode localizar manchas de flores que possuem quantidades minúsculas de pólen"},

{'ID' : 13,
'Sprite' : "Sprites/013-m.png",
'Nome' : "Weedle", 'Tipo_1' : "Inseto", 'Tipo_2' : "Venenoso",
'Peso' : 3.2, 'Altura' : 0.3,
'Descricao' : "Pokemon Lagarta Peluda",
'Info' : 'Come seu peso nas folhas todos os dias. Afasta os atacantes com a agulha na cabeça'},

{'ID' : 14,
'Sprite' : "Sprites/014-m.png",
'Nome' : "Kakuna", 'Tipo_1' : "Inseto", 'Tipo_2' : "Venenoso",
'Peso' : 10, 'Altura' : 0.6,
'Descricao' : "Pokemon Pupa",
'Info' : "Enquanto aguarda a evolução, esconde-se de predadores sob folhas e em recantos de galhos"},

{'ID' : 15,
'Sprite' : "Sprites/015-m.png",
'Nome' : "Beedrill", 'Tipo_1' : "Inseto", 'Tipo_2' : "Venenoso",
'Peso' : 29.5, 'Altura' : 1,
'Descricao' : "Pokemon Abelha venenosa",
'Info' : "Seu melhor ataque envolve voar em alta velocidade, golpear com agulhas de veneno e depois voar"},

{'ID' : 16,
'Sprite' : "Sprites/016-m.png",
'Nome' : "Pidgey", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 1.8, 'Altura' : 0.3,
'Descricao' : "Pokemon Passarinho",
'Info' : "É dócil e prefere evitar conflitos. Se pertubardo, no entanto, pode ferozmente reagir"},

{'ID' : 17,
'Sprite' : "Sprites/017-m.png",
'Nome' : "Pidgeotto", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 30, 'Altura' : 1.1,
'Descricao' : "Pokemon Passaro",
'Info' : "Voa sobre sue vasto território em busca de presas, derrubando-o com suas garras altamente desenvolvidas"},

{'ID' : 18,
'Sprite' : "Sprites/018-m.png",
'Nome' : "Pidgeot", 'Tipo_1' : "Voador", 'Tipo_2' : "Normal",
'Peso' : 39.5, 'Altura' : 1.5,
'Descricao' : "Pokemon Passaro",
'Info' : "Voa sobre sue vasto território em busca de presas, derrubando-o com suas garras altamente desenvolvidas"},

{'ID' : 19,
'Sprite' : "Sprites/019-m.png",
'Nome' : "Rattata", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 3.5, 'Altura' : 0.3,
'Descricao' : "Pokemon rato",
'Info' : "Ele procura comida o dia todo. Roe obejtos duros para desgastar suas presas, que crescem constantemente durante sua vida"},

{'ID' : 20,
'Sprite' : "Sprites/020-m.png",
'Nome' : "Raticate", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 18.5, 'Altura' : 0.7,
'Descricao' : "Pokemon Ratazana",
'Info' : "Com suas presas longas, este pokemon surpreendemente viloento pode roer até mesmo concreto espesso com facilidade"},

{'ID' : 21,
'Sprite' : "Sprites/021-m.png",
'Nome' : "Spearow", 'Tipo_1' : "Voador", 'Tipo_2': "Normal",
'Peso' : 2, 'Altura' : 0.3,
'Descricao' : "Pokemon Passarinho",
'Info' : "Bate suas pequenas asas ocupadas para voar. Usando o bico, ele procura presas na grama"},

{'ID' : 22,
'Sprite' : "Sprites/022-m.png",
'Nome' : "Fearow", 'Tipo_1' : "Voador", "Tipo_2" : "Normal",
'Peso' : 38, 'Altura' : 1.2,
'Descricao' : 'Pokemon Bico',
'Info' : "Ele tem resistência para voar o dia inteiro em suas asas largas. Ele luta usando seu bico afiado"},

{'ID' : 23,
'Sprite' : "Sprites/023-m.png",
'Nome' : "Ekans", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 6.9, 'Altura' : 2,
'Descricao' : "Pokemon Serpente",
'Info' : "Ele foge pela grama sem emitir nenhum som e atinge presas desavisadas por trás"},

{'ID' : 24,
'Sprite' : "Sprites/024-m.png",
'Nome' : "Arbok" , 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 65, 'Altura' : 3.5,
'Descricao' : "Pokemon Serpente",
'Info' : "O padrão em sua barriga é de intimidação. Ele restringe os inimigos enquanto eles estão congelados de medo"},

{'ID' : 25,
'Sprite' : "Sprites/025-m.png",
'Nome' : "Pikachu", 'Tipo_1' : "Elétrico", 'Tipo_2' : "",
'Peso' : 6, 'Altura' : 0.4,
'Descricao' : "Pokemon rato elétrico",
'Info' : "Ocasionalmente, usa um choque elétrico para recarregar um companheiro Pikachu que está em um estado enfraquecido"},

{'ID' : 26,
'Sprite' : "Sprites/026-m.png",
'Nome' : "Raichu", 'Tipo_1' : "Elétrico", 'Tipo_2' : "",
'Peso' : 30, 'Altura' : 0.8,
'Descricao' : "Pokemon rato elétrico",
'Info' : "Sua cauda descarrega eletricidade no chão, protegendo-a de ficar chocada"},

{'ID' : 27,
'Sprite' : "Sprites/027-m.png",
'Nome' : "Sandshrew", 'Tipo_1' : "Terra", 'Tipo_2' : "",
'Peso' : 12, 'Altura' : 0.6,
'Descricao' : "Pokemon Tatu",
'Info' :"Cava tocas profundas para viver. Quando em perigo, enrola o corpo para resistir a ataques"},

{'ID' : 28,
'Sprite' : "Sprites/028-m.png",
'Nome' : "Sandslash", 'Tipo_1' : "Terra", 'Tipo_2' : "", 
'Peso' : 29.5, 'Altura' : 1,
'Descricao' : "Pokemon Tatu",
'Info' : "Os espigões em seu corpo são compostos de sua pele endurecida. Ele rola e ataca os inimigos com seus espinhos"},

{'ID' : 29,
'Sprite' : "Sprites/029.png",
'Nome' : "Nidoran ♀", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 7, 'Altura' : 0.4,
'Descricao' : "Pokemon agulha venenosa",
'Info' : "Embora não prefira lutar, mesmo uma gota do veneno que secreta das farpas pode ser fatal"},

{'ID' : 30,
'Sprite' : "Sprites/030.png",
'Nome' : "Nidorina", 'Tipo_1' : "Venenoso", 'Tipo_2' : "", 
'Peso' : 20, 'Altura' : 0.8,
'Descricao' : "Pokemon agulha venenosa",
'Info' : "Quando percebe o perigo, levanta todas as farpas do corpo. Essas farpas crescem mais lentamente que Nidorinos"},

{'ID' : 31,
'Sprite' : "Sprites/031.png",
'Nome' : "Nidoqueen", 'Tipo_1' : "Terra", 'Tipo_2' : "Venenoso",
'Peso' : 60, 'Altura' : 1.3,
'Descricao' : "Pokemon Broca",
'Info' : "Seu corpo inteiro é blindado com escamas duras. Protegerá os jovens em sua toca com sua vida."},

{'ID' : 32,
'Sprite' : "Sprites/032.png",
'Nome' : "Nidoran ♂", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 9, 'Altura' : 0.5,
'Descricao' : "Pokemon agulha venenosa",
'Info' : "Ele examina seus arredores levantando as orelhas para fora da grama. Seu chifre tóxico é para proteção"},

{'ID' : 33,
'Sprite' : "Sprites/033.png",
'Nome' : "Nidorino", 'Tipo_1' : "Venenoso", 'Tipo_2' : "",
'Peso' : 19.5, 'Altura' : 0.9,
'Descricao' : "Pokemon agulha venenosa",
'Info' : "Tem uma disposição violenta e apunhala os inimigos com seu chifre, que exala veneno após o impacto"},

{'ID' : 34,
'Sprite' : "Sprites/034.png",
'Nome' : "Nidoking", 'Tipo_1' : "Terra", 'Tipo_2': "Venenoso",
'Peso' : 62, 'Altura' : 1.4,
"Descricao" : "Pokemon Broca",
'Info' : "Um balanço de sua poderosa cauda pode quebrar um poste telefônico como se fosse um palito de fósforo"},

{'ID' : 35,
'Sprite' : "Sprites/035-m.png",
'Nome' : "Clefairy", 'Tipo_1' : "Fada", 'Tipo_2' : "",
'Peso' : 7.5, 'Altura' : 0.6,
'Descricao' : "Pokemon Fada",
'Info' : "Nas noites de lua cheia, Clefairy se reúne e dança. Tomar banho ao luar os faz flutuar"},

{'ID' : 36,
'Sprite' : "Sprites/036-m.png",
'Nome' : "Clefable", 'Tipo_1' : "Fada", 'Tipo_2' : "",
'Peso' : 40, 'Altura' : 1.3,
'Descricao' : "Pokemon Fada",
'Info' : "Seus ouvidos são sensíveis o suficiente para ouvir um alfinete cair a mais de um quilômetro de distância, então geralmente são encontrados em locais calmos"},

{'ID' : 37,
'Sprite' : "Sprites/037-m.png",
'Nome' : "Vulpix", 'Tipo_1' : "Fogo", 'Tipo_2' : "",
'Peso' : 9.9, 'Altura' : 0.6,
'Descricao' : "Pokemon Raposa",
'Info' : "À medida que cada cauda cresce, seu pêlo se torna mais brilhante. Quando segurado, parece um pouco quente"},

{'ID' : 38,
'Sprite' : "Sprites/038-m.png",
'Nome' : "Ninetales", 'Tipo_1' : "Fogo", 'Tipo_2' : "", 
'Peso' : 19.9, 'Altura' : 1.1,
'Descricao' : "Pokemon Raposa",
'Info' : "Cada uma de suas nove caudas é imbuída de poder sobrenatural e pode viver por mil anos"},

{'ID' : 39,
'Sprite' : "Sprites/039-m.png",
'Nome' : "Jigglypuff", 'Tipo_1' : "Fada", 'Tipo_2': "Normal",
'Peso' : 5.5, 'Altura' : 0.5,
'Descricao' : "Pokemon Balao",
'Info' : "Olhar para seus olhos redondos e bonitos faz com que comece a cantar uma música que os ouvintes agradáveis ​​não podem deixar de adormecer"},

{'ID' : 40,
'Sprite' : "Sprites/040-m.png",
'Nome' : "Wigglytuff", 'Tipo_1' : "Fada", 'Tipo_2': "Normal",
'Peso' : 12, 'Altura' : 1,
'Descricao' : "Pokemon Balao",
'Info' : "Sua pele fina é tão agradável que aqueles que a tocam acidentalmente não conseguem tirar as mãos"},

{'ID' : 41,
'Sprite' : "Sprites/041-m.png",
'Nome' : "Zubat", 'Tipo_1' : "Venenoso", 'Tipo_2': "Voador",
'Peso' : 7.5, 'Altura' : 0.8,
'Descricao' : "Pokemon Morcego",
'Info' : "Ele não precisa de olhos, porque emite ondas ultrassônicas para verificar seus arredores enquanto voa"},

{'ID' : 42,
'Sprite' : "Sprites/042-m.png",
'Nome' : "Golbat", 'Tipo_1' : "Venenoso", 'Tipo_2' : "Voador",
'Peso' : 55, 'Altura' : 1.6,
'Descricao' : "Pokemon Morcego",
'Info' : "Voando na calada da noite, afunda suas presas em suas presas e drena uma quantidade quase fatal de sangue"},

{'ID' : 43,
'Sprite' : "Sprites/043-m.png",
'Nome' : "Oddish", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 5.4, 'Altura' : 0.5,
'Descricao' : 'Pokemon Erva',
'Info' : "Costuma plantar os pés de raiz no chão durante o dia e semeia sementes enquanto caminha à noite"},

{'ID' : 44,
'Sprite' : "Sprites/044-m.png",
'Nome' : "Gloom", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 8.6, 'Altura' : 0.8,
'Descricao' : "Pokemon Erva",
'Info' : "O mel que escorre da boca cheira tão atroz que pode enrolar o nariz a mais de um quilômetro de distância"},

{'ID' : 45,
'Sprite' : "Sprites/045-m.png",
'Nome' : "Vileplume", 'Tipo_1' : "Planta", 'Tipo_2' : "Venenoso",
'Peso' : 18.6, 'Altura' : 1.2,
'Descricao' : "Pokemon Flor",
'Info' : "Suas pétalas são as maiores do mundo. Enquanto caminha, espalha pólen extremamente alergênico"},

{'ID' : 46,
'Sprite' : "Sprites/046-m.png",
'Nome' : "Paras", 'Tipo_1' : "Planta", 'Tipo_2' : "Inseto",
'Peso' : 5.4, 'Altura' : 0.3,
'Descricao' : "Pokemon Cogumelo",
'Info' : "Cogumelos chamados tochukaso crescem nas costas. Eles crescem junto com o anfitrião Paras"},

{'ID' : 47,
'Sprite' : "Sprites/047-m.png",
'Nome' : "Parasect", 'Tipo_1' : "Planta", 'Tipo_2': "Inseto",
'Peso' : 29.5, 'Altura' : 1,
'Descricao' : "Pokemon Cogumelo",
'Info' : "Um cogumelo maior que o corpo hospedeiro controla o parasita. Espalha esporos venenosos"},

{'ID' : 48,
'Sprite' : "Sprites/048-m.png",
'Nome' : "Venonat",  'Tipo_1' : "Inseto", 'Tipo_2': "Venenoso",
'Peso' : 30, 'Altura' : 1,
'Descricao' : "Pokemon Inseto",
'Info' : "Seus grandes olhos são na verdade aglomerados de pequenos olhos. À noite, seu Tipo_1 é atraído pela luz."},

{'ID' : 49,
'Sprite' : "Sprites/049-m.png",
'Nome' : "Venomoth", 'Tipo_1' : "Inseto", 'Tipo_2' : "Venenoso",
'Peso' : 12.5, 'Altura' : 1.5,
'Descricao' : "Pokemon traca venenosa",
'Info' : "Ele bate as asas para espalhar escamas semelhantes a poeira. As escamas liberam toxinas se entrarem em contato com a pele"},

{'ID' : 50,
'Sprite' : "Sprites/050-m.png",
'Nome' : "Diglett", 'Tipo_1' : "Terra", 'Tipo_2' : "",
'Peso' : 0.8, 'Altura' : 0.2,
'Descricao' : "Pokemon Toupeira",
'Info' : "Um Pokémon que vive no subsolo. Por causa de seu habitat escuro, é repelido pela luz do sol"},

{'ID' :  51,
'Sprite' : "Sprites/051-m.png",
'Nome' : "Dugtrio", 'Tipo_1' : "Terra", 'Tipo_2' : "",
'Peso' : 33.3, 'Altura' : 0.7,
'Descricao' : "Pokemon Toupeira",
'Info' : 'Suas três cabeças se movem alternadamente, conduzindo-o através de solos difíceis a profundidades supeiores a 100 quilômetros'},

{'ID' : 52,
'Sprite' : "Sprites/052-m.png",
'Nome' : "Meowth", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 4.2, 'Altura' : 0.4,
'Descricao' : "Pokemon Gatuno",
'Info' : "É de natureza nortuna. Se encontrar algo brilhante, seus olhos brilham intensamente"},

{'ID' : 53,
'Sprite' : "Sprites/053-m.png",
'Nome' : "Persian", 'Tipo_1' : "Normal", 'Tipo_2' : "",
'Peso' : 32, 'Altura' : 1,
'Descricao' : "Pokemon Gato Siamês",
'Info' : "Um pokémon muito arrogante. Entre os fãs, o tamanho da jóia em sua testa é um assunto muito discutido"},

{'ID' : 54,
'Sprite' : "Sprites/054-m.png",
'Nome' : "Pysduck" , 'Tipo_1' : "Água", 'Tipo_2' : "",
'Peso' : 19.6, 'Altura' : 0.8,
'Descricao' : "Pokemon Pato",
'Info' : "Quando as dores de cabeça estimulam suas células cerebrais, que geralmente são inativas, ele pode usar um poder misterioso"},

]


for id_pokemon, pokemon in enumerate(pokemon_lista):
         print(f'#{id_pokemon + 1:0>3} - {pokemon["Tipo_1"]} / {pokemon["Tipo_2"]}')
